export './colors/app_colors.dart';
export './string/leadstage.dart';
export './typography_constants.dart';
export './app_assets.dart';

export './widgets/widgets.dart';

 final List<String> leadGroup = [
    'Paris Leads',
    'Insurance Leads',
    'Real Estate Leads',
    'Mortgage Leads',
    'Credit Repair Leads',
    'Solar Leads',
    'Home Security Leads',
    'Home Improvement Leads',
    'HVAC Leads',
    'Auto Warranty Leads',
    'Auto Insurance Leads',
    'Auto Finance Leads',
    'Auto Leads',
    'Debt Leads',
    'Student Loan Leads',
    'Payday Leads',
    'Tax Leads',
    'Health Insurance Leads',
    'Final Expense Leads',
    'Medicare Leads',
    'Life Insurance Leads',
    'Solar Leads',
    'Home Security Leads',
    'Home Improvement Leads',
    'HVAC Leads',
    'Auto Warranty Leads',
    'Auto Insurance Leads',
    'Auto Finance Leads',
    'Auto Leads',
    'Debt Leads',
    'Student Loan Leads',
    'Payday Leads',
    'Tax Leads',
    'Health Insurance Leads',
    'Final Expense Leads',
    'Medicare Leads',
    'Life Insurance Leads',
    'Solar Leads',
    'Home Security Leads',
    'Home Improvement Leads',
    'HVAC Leads',
    'Auto Warranty Leads',
    'Auto Insurance Leads',
    'Auto Finance Leads',
    'Auto Leads',
    'Debt Leads',
    'Student Loan Leads',
    'Payday Leads',
    'Tax Leads',
    'Health Insurance Leads',
    'Final Expense Leads',
    'Medicare Leads',
    'Life Insurance Leads'
  ];